app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('education.urls')),
]

app/education/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('schools/', views.school_list, name='school-list'),
    path('schools/<int:school_id>/', views.school_detail, name='school-detail'),
    path('students/', views.student_list, name='student-list'),
    path('students/<int:student_id>/', views.student_detail, name='student-detail'),

]

app/education/models.py
from django.db import models

from django.db import models
from django.utils import timezone


class School(models.Model):
    name = models.CharField(max_length=200)  # 길이 제한 있는 text
    description = models.TextField(blank=True)  # 길이가 무한인 text
    created_date = models.DateTimeField(default=timezone.now)  # date와 time을 저장해놓은 필드
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):  # 객체를 문자열로 정의하고 싶을 때 사용
        return self.name


class Student(models.Model):
    school = models.ForeignKey(
        School,
        on_delete=models.CASCADE,
    )
    name = models.CharField(max_length=200)  # 길이 제한 있는 text
    created_date = models.DateTimeField(default=timezone.now)  # date와 time을 저장해놓은 필드
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):  # 객체를 문자열로 정의하고 싶을 때 사용
        return self.name

app/education/views.py
from django.shortcuts import render

from education.models import School, Student


def index(request):
    return render(request, 'education/index.html')


def school_list(request):
    schools = School.objects.all()
    # print(schools)
    context = {
        'schools': schools,
    }
    return render(request, 'education/school_list.html', context)


def school_detail(request, school_id):
    school = School.objects.get(id=school_id)
    context = {
        'school': school
    }
    return render(request, 'education/school_detail.html', context)


def student_list(request):
    students = Student.objects.all()
    context = {
        'students': students,
    }
    return render(request, 'education/student_list.html', context)


def student_detail(request, student_id):

    student = Student.objects.get(id=student_id)
    context = {
        'student': student,
    }
    return render(request, 'education/student_detail.html', context)

app/education/templates/education/index.html
<h3><a href="{% url 'school-list' %}">학교</a></h3>
<h3><a href="{% url 'student-list' %}">학생</a></h3>
<p>왜 안넘어가지지..분명 전에는 넘어가졌는데...</p>

app/education/templates/education/school_detail.html
<h1>School Detail</h1>

<h3>{{ school.name }}</h3>
<p>{{ school.description }}</p>

{% for student in school.student_set.all %}
    <a href="{% url 'student-detail' student.id %}">{{ student }}</a>
{% endfor %}

app/education/templates/education/school_list.html
<h1>School List</h1>

{% for school in schools %}
    <a href="{% url 'school-detail' school.id %}">{{ school }}</a>
{% endfor %}

app/education/templates/education/student_detail.html
<h1>Student Detail</h1>

<h3>{{ student.name }}</h3>

<a href="{% url 'school-detail' student.school.id %}">{{ student.school }}</a>
<p>{{ student.created_date }}</p>

app/education/templates/education/student_list.html
<h1>Student List</h1>

{% for student in students %}
    <a href="{% url 'student-detail' student.id %}">{{ student }}</a>
{% endfor %}